# Generated by Django 4.0.4 on 2022-04-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='fornecador',
            new_name='fornecedor',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='notafiscal',
            new_name='nota_fiscal',
        ),
    ]
